# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: precise
language: cpp

git:
  depth: 3

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: 
       - COMPILER=g++-4.9
       - ARCH=arm
         matrix:
         - PKGID=100
         - PKGID=200 

before_install:
  - sudo apt-get update -qq

script:
  - "bash -ex ./tools/test/travis-ci.sh"
